name: "🆕 Feature or improvement"
description: Suggest a feature or improvement for the TestRail CLI
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like the TestRail CLI to be able to do?
      description: A clear description of the feature or improvement, including files and other examples if it applies.
      placeholder: I'd like to be able to...
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why is this feature necessary on the TestRail CLI?
      description: Please state your use case so we can assess if this is something valuable.
      placeholder: I want this because...
  - type: textarea
    id: other
    attributes:
      label: More Details
      placeholder: Other details you would like to include.
  - type: dropdown
    id: will-implement
    attributes:
      label: Interested in implementing it yourself?
      description: Please let us know if you want to contribute by creating the solution yourself.
      options:
        - "Yes"
        - "No"
    validations:
      required: true